sprite:
  name: "background"
  pos: [960, 540]
  file: "../ressources/Assets/Menu/background-default.png"
  rotation: 0
  scale: 1
  origin: [960, 540]
buttontristate:
  name: "quit"
  pos: [1700, 50]
  scale: 1
  origin: [0, 0]
  rotation: 0
  file: "../ressources/Assets/Menu/Button.png"
  rect: [1105, 2615, 193, 180]